version: '3.4'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-dvp_localstack}'
    image: localstack/localstack:1.1.0
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,sqs,dynamodb
      - AWS_ACCESS_KEY_ID=test_access_key
      - AWS_SECRET_ACCESS_KEY=test_secret_key
      - DEBUG=0
      - NO_PROXY
      - DATA_DIR=/tmp/localstack/data

    volumes:
      - './localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./init-scripts:/docker-entrypoint-initaws.d
