/* tslint:disable */
/* eslint-disable */
/**
 * DVP Admin API
 * Admin API for the Digital Verification Platform
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * An object containing references to the source of an error.
 * @export
 * @interface ErrorSource
 */
export interface ErrorSource {
    /**
     * A JSON Pointer which describes which property in the request object to which an error message relates.  For more details on JSON pointers see [RFC6901](https://tools.ietf.org/html/rfc6901).
     * @type {string}
     * @memberof ErrorSource
     */
    'pointer'?: string;
    /**
     * Describes the location of the data to which the error message is related.  - **\"REQUEST\"** - Indicates the message relates to a _property_ within the request   object. The `pointer` property should be populated in this case. - **\"QUERY\"** - Indicates the message relates to a _query_ parameter. The `parameter`   property should be populated in this case. - **\"ID\"** - Indicates the message relates to the identifier of the REST resource. The   `parameter` property _may optionally_ be populated in this case.
     * @type {string}
     * @memberof ErrorSource
     */
    'location'?: ErrorSourceLocationEnum;
    /**
     * A string indicating which URI query parameter caused the error.
     * @type {string}
     * @memberof ErrorSource
     */
    'parameter'?: string;
}

export const ErrorSourceLocationEnum = {
    Request: 'REQUEST',
    Query: 'QUERY',
    Id: 'ID'
} as const;

export type ErrorSourceLocationEnum = typeof ErrorSourceLocationEnum[keyof typeof ErrorSourceLocationEnum];

/**
 * A schema for the `errors` array.
 * @export
 * @interface ErrorsArray
 */
export interface ErrorsArray {
    /**
     * 
     * @type {Array<Error>}
     * @memberof ErrorsArray
     */
    'errors'?: Array<Error>;
}
/**
 * The response returned when one or more errors have been encountered.
 * @export
 * @interface ErrorsResponseSchema
 */
export interface ErrorsResponseSchema {
    /**
     * 
     * @type {Array<Error>}
     * @memberof ErrorsResponseSchema
     */
    'errors': Array<Error>;
}
/**
 * An object containing the details of a particular error.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * A unique identifier for the error occurrence, to provide traceability in application logs.
     * @type {string}
     * @memberof ModelError
     */
    'id'?: string;
    /**
     * A provider-specific or enterprise defined error code. Codes must be in uppercase.
     * @type {string}
     * @memberof ModelError
     */
    'code': string;
    /**
     * A provider-specific or enterprise defined error message.
     * @type {string}
     * @memberof ModelError
     */
    'detail': string;
    /**
     * 
     * @type {ErrorSource}
     * @memberof ModelError
     */
    'source'?: ErrorSource;
    /**
     * A URL which leads to further details about the error (e.g. A help page).
     * @type {string}
     * @memberof ModelError
     */
    'helpUrl'?: string;
    /**
     * Help text which can provide further assistance on the error.
     * @type {string}
     * @memberof ModelError
     */
    'helpText'?: string;
}
/**
 * Pagination data object
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {string}
     * @memberof Pagination
     */
    'nextCursor'?: string;
    /**
     * 
     * @type {string}
     * @memberof Pagination
     */
    'prevCursor'?: string;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'limit'?: number;
}

